server:
  port: 7004


eureka:
  instance:
    hostname: eureka7004.com
  client:
    #声明自己是服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/
