server:
  port: 80

# 服务别名---zookeeper注册中心名称
spring:
  application:
    name: cloud-provider-order80
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding-utr-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root